### ISSUE TITLE
Fix `return-type` and `comment` warnings.

### ISSUE THREAD

**Issue by miladHakimi** [googlestadia/performance-layers#104]
Some of the current warnings are caught as errors when the code gets imported.
https://github.com/google/vulkan-performance-layers/commit/7787cbaf75ed282ec440c4ba3d006ab26cded973

We would like to catch all of those warnings in the CI. To do that, we enable all the warnings and treat them as errors by setting `-Werror`. 
`comment` and `return-type` are the existing unhandled warnings (excluded from `-Werror`) that do not break the imports but we would like to fix them.

**Comment by miladHakimi** [comment]
Regarding the `comment` warnings:
https://stackoverflow.com/questions/19105350/what-is-the-meaning-of-multi-line-comment-warnings-in-c

**Comment by kuhar** [comment]
@miladHakimi how can I reproduce these warnings? I don't see them in the CI logs: https://github.com/google/vulkan-performance-layers/actions/runs/3388990554/jobs/5631591262#step:3:1599

**Comment by miladHakimi** [comment]
> @miladHakimi how can I reproduce these warnings? I don't see them in the CI logs: https://github.com/google/vulkan-performance-layers/actions/runs/3388990554/jobs/5631591262#step:3:1599

Remove `-Wno-comment` or `-Wno-return-type` from `build.Dockerfile`.
