### ISSUE TITLE
Event logging implementation for the Chrome Trace Event format.

### ISSUE THREAD

**Issue by miladHakimi** [googlestadia/performance-layers#130]
Here is the base Trace Event format:
```json
{
  "name": "myName",
  "cat": "category,list",
  "ph": "B",
  "ts": 12345,
  "pid": 123,
  "tid": 456,
  "args": {
    "someArg": 1,
    "anotherArg": {
      "value": "my value"
    }
  }
```
Not all the fields are required and we can skip `cat`, `pid`, `tid`, and `args`.  But, we might need additional fields based on the phase (`ph`) we specify. Since our main goal is to show duration, the phase should be `X` which indicates an event with duration  in Trace Event (a Complete event). This event requires an additional duration (`dur`) field. A simple Complete event would look like this:
```json
{ "name": "myName", "ph": "X", "ts": 12345, "dur": 123}
``` 
Current `Event` class does not have a "phase" and putting the phase as an attribute might mess things up because we have to change the other loggers to ignore it. I suggest the following code:
```c++
enum Phase { Complete };

class TraceEvent: public Event { 
 public:
  Phase GetPhase() { return phase_;};
  virtual Duration GetDuration() { ... }
 private:
  Phase phase_;
};

std::string TraceEventToStr(TraceEvent *event) {
    std::stringstream event_str;
    int64_t timestamp_ms = ToMilliseconds(event->GetTimestamp());
    event_str << "{" << std::quoted("name") << ":" << std::quoted(event->GetName()) << std::quoted("ts") << ":" << timestamp_ms << "}";
    if (event->GetPhase() == Phase::Complete)
        event_str << std::quoted("ph") << ":" << std::quoted("X") << "," << std::quoted("dur") << ":" << ToMilliseconds(event->GetDuration());

    event_str << "},";    
    return event_str.str();    
}

```
To get the duration, the events that are created as a `TraceEvent` have already a duration attribute. There are a couple of ways to get that attribute:
- Keep a pointer to the duration attribute in the `TraceEvent` as a private variable. This approach might require the least modification to the previous code.
- Move the duration attribute to the `Event` class so that all the `Event`s have duration. The default duration should be 0. This might not make sense especially for the events that do not have any duration (e.g., the events indicating the start of a layer).   We should also modify the loggers as well because the durations are moved out of the attribute vector and we can't print them by just iterating over the attributes.
- Add a `GetAttributeByName()` method to the event to iterate over the attributes and return the matched one. The good thing about it is that we don't need to duplicate things or change tons of code. But the caveat might be the performance since we have to do it for each event. 

The `TraceEventLogger` takes a `TraceEvent`, converts it to a 1 line string using the mentioned function and logs it to the output.  It also overrides the `StartEvent()` to print an open bracket to the file.

Then we need a `DataLayer` with  a `TraceEventLogger` that runtime and compile time layer use.

**Comment by kuhar** [comment]
Thanks for writing this down:

> Current Event class does not have a "phase" and putting the phase as an attribute might mess things up because we have to change the other loggers to ignore it. I suggest the following code:

IMO we shouldn't discard this solution prematurely. I find it natural for loggers to care about some attributes and discard the rest.

Similarly, having an explicit phase attribute could inform the `TraceLogger` to log some events and skip the others.

> std::string TraceEventToStr(TraceEvent *event)

It's unclear to me how this would work with the existing implementation. We have no mechanism to tell if an event is a `TraceEvent` or not. Although it shouldn't be too hard to to add this.

**Comment by miladHakimi** [comment]
> Similarly, having an explicit phase attribute could inform the `TraceLogger` to log some events and skip the others.
> 
> >
For this, I was thinking of using the filter logger and filtering them based on the log level.

**Comment by miladHakimi** [comment]
> It's unclear to me how this would work with the existing implementation. We have no mechanism to tell if an event is a `TraceEvent` or not. Although it shouldn't be too hard to to add this.

Currently, the events in the compile time and runtime layer are extended from `Event`. Instead we can extend them from `TraceEvent`. Those layers will have a `LayerDataWithTraceLogger` which accepts a `TraceEvent`, converts it to a string using this function and logs it.
Isn't it gonna be a compile error if we pass an event which is not a `TraceEvent` to this function?

**Comment by kuhar** [comment]
> > Similarly, having an explicit phase attribute could inform the `TraceLogger` to log some events and skip the others.
> > >
> 
> For this, I was thinking of using the filter logger and filtering them based on the log level.

> Currently, the events in the compile time and runtime layer are extended from `Event`. Instead we can extend them from `TraceEvent`. Those layers will have a `LayerDataWithTraceLogger` which accepts a `TraceEvent`, converts it to a string using this function and logs it.

I assumed we wanted to maintain that the same event class can be logged by all loggers (modulo ones that don't care about an event), and that logging happens when we call `AddEvent(Event *)`. And in general I don't think we should duplicate event types (e.g., having 2 shader creation events, one  for CSV/Common and one for Trace). 

If you add a new base event type that can only be passed to `TraceLogger`, you would also have to teach to extend the whole logger hierarchy (broadcast, filter, and test code).

**Comment by miladHakimi** [comment]
> > > Similarly, having an explicit phase attribute could inform the `TraceLogger` to log some events and skip the others.
> > > >
> > 
> > 
> > For this, I was thinking of using the filter logger and filtering them based on the log level.
> 
> > Currently, the events in the compile time and runtime layer are extended from `Event`. Instead we can extend them from `TraceEvent`. Those layers will have a `LayerDataWithTraceLogger` which accepts a `TraceEvent`, converts it to a string using this function and logs it.
> 
> I assumed we wanted to maintain that the same event class can be logged by all loggers (modulo ones that don't care about an event), and that logging happens when we call `AddEvent(Event *)`. And in general I don't think we should duplicate event types (e.g., having 2 shader creation events, one for CSV/Common and one for Trace).
> 
> If you add a new base event type that can only be passed to `TraceLogger`, you would also have to teach to extend the whole logger hierarchy (broadcast, filter, and test code).

Yeah. You're right. I'll re-think about it.

**Comment by miladHakimi** [comment]
We want these two types of events:
```json 
{ "name": "Complete Event", "cat": "pipeline", "ph": "X", "ts": 12345, "pid": 123, "tid": 456, "dur": 123,  "args":  { "someArg": [1, 2]} }

{ "name": "Instant Event", "cat": "start event", "ph": "i", "ts": 12345, "pid": 123, "tid": 456, "s": "g",  "args":  {} }
```
We can have a compound attribute constructed from our current set of  primitive attributes and used by the `TraceEventLogger` and ignored by other loggers. To support `Instant Event`s and `Complete Event`s the compound event has to have `cateogry`, `phase`, `pid`, and `tid`. We also might want to consider having a vector of attributes for the optional attributes (e.g., shader hashes) or the ones that might be required based on the event type (e.g., `duration` or `scope`). 
All events have a timestamp attribute which shows the end of an event. The visualizer associates the timestamp with the beginning of the event so the `Complete Event`s have to calculate the start timestamp by subtracting duration from the  event's timestamp. Hence, the helper function that takes the attribute and converts it to a string (e.g., `TraceAttrToString()`), should also receive the timestamp from the caller.

The compound attribute could be like this:
```c++
class TraceEventAttribute : public Attribute {
 public:
  static constexpr ValueType id_ = ValueType::kTraceEvent;

  TraceEventAttribute(const char *name, const char *cat,
                      const char *phase, int64_t pid,
                      int64_t tid, std::initializer_list<Attribute *> args)
      : Attribute(name, ValueType::kTraceEvent),
        category_("cat", cat),
        phase_("ph", phase),
        pid_("pid", pid),
        tid_("tid", tid)
  {
    args_ = {args.begin(), args.end()};
  }

 // Getter methods

 private:
  StringAttr category_;
  StringAttr phase_;
  Int64Attr pid_;
  Int64Attr tid_;
  std::vector<Attribute *> args_;
};

```
Each event scans the `args` vector based on `phase` to extract the arguments it wants. Since `args` is small, scanning it shouldn't have much overhead.
